defaults: &defaults
  adapter: postgresql
  user: web
  password: web01
  host: spark4.thedevranch.net

development:
  <<: *defaults
  database: heart_rate_development

test:
  <<: *defaults
  database: heart_rate_test

production:
  <<: *defaults
  database: heart-rate-production
