defaults: &defaults
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root

development:
  <<: *defaults
  database: heart-rate-development

test:
  <<: *defaults
  database: heart-rate-test

production:
  <<: *defaults
  database: heart-rate-production
