defaults: &defaults
  adapter: postgresql

development:
  <<: *defaults
  database: heart-rate-development

test:
  <<: *defaults
  database: heart-rate-test

production:
  <<: *defaults
  database: heart-rate-production
